owner: jon-blanco
repo: canivoteforu-status
user-agent: jon-blanco

assignees:
  - jon-blanco

sites: []

status-website:
  cname: status.canivoteforu.com
  name: CanIVoteForU Status
  introTitle: "**CanIVoteForU** status"
  introMessage: Current status of CanIVoteForU.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
